package jfcraft.data;

/** Noise test panel
 *
 * @author pquiring
 */

import java.awt.*;
import javax.swing.*;
import java.util.*;

import javaforce.*;

public class NoiseTestPanel extends javax.swing.JPanel {

  /**
   * Creates new form NoiseTest
   */
  public NoiseTestPanel() {
    initComponents();
    generate();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    mode = new javax.swing.JComboBox();
    canvas = new java.awt.Canvas() {
      public void paint(java.awt.Graphics g) {
        if (img == null) return;
        g.drawImage(img.getImage(), 0, 0, null);
      }
    };
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    octaves = new javax.swing.JSpinner();
    persist = new javax.swing.JSpinner();
    scale = new javax.swing.JSpinner();
    cx = new javax.swing.JSpinner();
    jLabel9 = new javax.swing.JLabel();
    cy = new javax.swing.JSpinner();
    cz = new javax.swing.JSpinner();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    jLabel13 = new javax.swing.JLabel();
    jLabel14 = new javax.swing.JLabel();
    seed = new javax.swing.JTextField();
    jLabel15 = new javax.swing.JLabel();
    jLabel16 = new javax.swing.JLabel();
    base = new javax.swing.JSpinner();
    yscale = new javax.swing.JSpinner();
    jButton1 = new javax.swing.JButton();
    angle = new javax.swing.JSlider();
    jLabel17 = new javax.swing.JLabel();
    threshold = new javax.swing.JSpinner();

    mode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2D", "3D", "Caves" }));
    mode.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        modeItemStateChanged(evt);
      }
    });
    mode.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        modeActionPerformed(evt);
      }
    });

    jLabel1.setText("Octaves");

    jLabel2.setText("Persist");

    jLabel3.setText("Scale");

    jLabel4.setText("(1-16)");

    jLabel5.setText("(0.0 - 1.0)");

    jLabel6.setText("(0.0 - 1.0)");

    jLabel7.setText("X:");

    jLabel8.setText("Z:");

    octaves.setModel(new javax.swing.SpinnerNumberModel(2, 1, 16, 1));
    octaves.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        octavesStateChanged(evt);
      }
    });

    persist.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.5f), Float.valueOf(0.0f), Float.valueOf(1.0f), Float.valueOf(0.1f)));
    persist.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        persistStateChanged(evt);
      }
    });

    scale.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.01f), Float.valueOf(0.0f), Float.valueOf(1.0f), Float.valueOf(0.01f)));
    scale.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        scaleStateChanged(evt);
      }
    });

    cx.setModel(new javax.swing.SpinnerNumberModel(0, -100, 100, 1));
    cx.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        cxStateChanged(evt);
      }
    });

    jLabel9.setText("Y:");

    cy.setModel(new javax.swing.SpinnerNumberModel(0, -100, 100, 1));
    cy.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        cyStateChanged(evt);
      }
    });

    cz.setModel(new javax.swing.SpinnerNumberModel(0, -100, 100, 1));
    cz.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        czStateChanged(evt);
      }
    });

    jLabel10.setText("+ / - integer");

    jLabel11.setText("+ / - integer");

    jLabel12.setText("+ / - integer");

    jLabel13.setText("Mode");

    jLabel14.setText("seed");

    seed.setText("0");

    jLabel15.setText("base");

    jLabel16.setText("y scale");

    base.setModel(new javax.swing.SpinnerNumberModel(128, 0, 256, 1));
    base.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        baseStateChanged(evt);
      }
    });

    yscale.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(128.0f), Float.valueOf(0.0f), Float.valueOf(128.0f), Float.valueOf(1.0f)));
    yscale.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        yscaleStateChanged(evt);
      }
    });

    jButton1.setText("Generate");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    angle.setMaximum(128);
    angle.setOrientation(javax.swing.JSlider.VERTICAL);
    angle.setToolTipText("");
    angle.setValue(128);
    angle.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        angleStateChanged(evt);
      }
    });

    jLabel17.setText("3d thres");

    threshold.setModel(new javax.swing.SpinnerNumberModel(128, 0, 256, 1));
    threshold.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        thresholdStateChanged(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(canvas, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel1)
              .addComponent(jLabel2)
              .addComponent(jLabel3)
              .addComponent(jLabel7)
              .addComponent(jLabel9)
              .addComponent(jLabel8)
              .addComponent(jLabel13)
              .addComponent(jLabel15)
              .addComponent(jLabel16)
              .addComponent(jLabel14))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(yscale, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(scale)
                  .addComponent(persist)
                  .addComponent(octaves)
                  .addComponent(cx, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                  .addComponent(cy)
                  .addComponent(cz)
                  .addComponent(mode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel12)
                  .addComponent(jButton1)
                  .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(jLabel4)
                      .addComponent(jLabel5)
                      .addComponent(jLabel6)
                      .addComponent(jLabel10)
                      .addComponent(jLabel11))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(angle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
              .addComponent(seed, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel17)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(threshold, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(canvas, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(mode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel13)
              .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(7, 7, 7)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel1)
                  .addComponent(jLabel4)
                  .addComponent(octaves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(persist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel2)
                  .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(scale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel3)
                  .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel7)
                  .addComponent(cx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel9)
                  .addComponent(cy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel8)
                  .addComponent(cz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(seed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel15)
                  .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
              .addComponent(angle, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel16)
              .addComponent(yscale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel17)
              .addComponent(threshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void modeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_modeActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    generate();
  }//GEN-LAST:event_jButton1ActionPerformed

  private void octavesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_octavesStateChanged
    generate();
  }//GEN-LAST:event_octavesStateChanged

  private void persistStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_persistStateChanged
    generate();
  }//GEN-LAST:event_persistStateChanged

  private void scaleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_scaleStateChanged
    generate();
  }//GEN-LAST:event_scaleStateChanged

  private void cxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cxStateChanged
    generate();
  }//GEN-LAST:event_cxStateChanged

  private void cyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cyStateChanged
    generate();
  }//GEN-LAST:event_cyStateChanged

  private void czStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_czStateChanged
    generate();
  }//GEN-LAST:event_czStateChanged

  private void baseStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_baseStateChanged
    generate();
  }//GEN-LAST:event_baseStateChanged

  private void yscaleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_yscaleStateChanged
    generate();
  }//GEN-LAST:event_yscaleStateChanged

  private void modeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_modeItemStateChanged
    generate();
  }//GEN-LAST:event_modeItemStateChanged

  private void angleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_angleStateChanged
    generate();
  }//GEN-LAST:event_angleStateChanged

  private void thresholdStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_thresholdStateChanged
    generate();
  }//GEN-LAST:event_thresholdStateChanged


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JSlider angle;
  private javax.swing.JSpinner base;
  private java.awt.Canvas canvas;
  private javax.swing.JSpinner cx;
  private javax.swing.JSpinner cy;
  private javax.swing.JSpinner cz;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JComboBox mode;
  private javax.swing.JSpinner octaves;
  private javax.swing.JSpinner persist;
  private javax.swing.JSpinner scale;
  private javax.swing.JTextField seed;
  private javax.swing.JSpinner threshold;
  private javax.swing.JSpinner yscale;
  // End of variables declaration//GEN-END:variables

  private JFImage img = new JFImage(256, 384);

  public void generate() {
    Noise noise = new Noise();
    Random rand = new Random();
    rand.setSeed(JF.atoi(seed.getText()));
    noise.init(rand, (Integer)octaves.getValue(), (Float)persist.getValue(), (Float)scale.getValue());
    img.fill(0, 0, 256, 384, 0xff000000, true);
    int clr = Color.gray.getRGB();
    img.line(0, 128, 128, 0, clr);
    img.line(0, 128, 128, 255, clr);
    img.line(128, 0, 255, 128, clr);
    img.line(128, 255, 255, 128, clr);

    img.line(0, 128, 0, 255, clr);
    img.line(255, 128, 255, 255, clr);

    img.line(0, 255, 128, 383, clr);
    img.line(128, 383, 255, 255, clr);
    float y_scale = (Float)yscale.getValue();
    int _base = (Integer)base.getValue();
    clr = Color.white.getRGB();
    int _cx = (Integer)cx.getValue() * 16;
    int _cy = (Integer)cy.getValue() * 16;
    int _cz = (Integer)cz.getValue() * 16;
    float _angle = (Integer)angle.getValue();
    _angle /= 128.0f;
    switch (mode.getSelectedIndex()) {
      case 0:
        //2d
        for(float x=0;x<128;x++) {
          for(float z=0;z<128;z++) {
            float y = (noise.noise_2d(x + _cx,z + _cz) * y_scale + _base) / 2.0f;
            float _x = x + z;
            float _y2 = -x * _angle + z * _angle + 256;
            float _y1 = _y2 - y;
            img.putPixel((int)_x, (int)_y1, clr);
          }
        }
        break;
      case 1:
        //3d
        int r,b,g;
        int _threshold = (Integer)threshold.getValue();
        for(float y=0;y<128;y+=3) {
          for(float x=0;x<128;x+=3) {
            for(float z=0;z<128;z+=3) {
              int a = (int)Math.abs(noise.noise_3d(x + _cx,y + _cy, z + _cz) * y_scale + _base);
              if (a <= _threshold) continue;
              a &= 0xff;
              float _x = x + z;
              float _y = 256 + (-x * _angle) + (z * _angle) - y;
  /*
              float o = 256 - a;
              a *= 256.0f;
              clr = img.getPixel((int)_x, (int)_y);
              r = (clr & 0xff0000) >> 16;
              g = (clr & 0xff00) >> 8;
              b = clr & 0xff;
              r = (int)(r * o + a) >> 8;
              g = (int)(g * o + a) >> 8;
              b = (int)(b * o + a) >> 8;
              clr = r << 16 + g << 8 + b;
  */
              clr = (a << 16) + (a << 8) + a;
              img.putPixel((int)_x, (int)_y, clr);
            }
          }
        }
        break;
      case 2:
        //Caves
        for(float x=0;x<128;x++) {
          for(float z=0;z<128;z++) {
            float y1 = (noise.noise_2d(x + _cx,z + _cz) * y_scale + _base) / 2.0f;
            float y2 = (noise.noise_2d(x + _cx + 1000,z + _cz + 1000) * y_scale + _base) / 2.0f;
            if (y1 < 32 || y1 > 35) continue;
//            if (y2 > 64) continue;
            float _x = x + z;
            float _y2 = -x * _angle + z * _angle + 256;
            float _y1 = _y2 - y1;
            img.putPixel((int)_x, (int)_y1, clr);
          }
        }
    }
    canvas.repaint();
  }

  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {public void run() {
      JFrame frame = new JFrame();
      frame.setSize(600, 500);
      frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      frame.setContentPane(new NoiseTestPanel());
      frame.setVisible(true);
    }});
  }
}
